title: Not Like Other Girls
logo: /assets/img/BLOGLogo.png
description: A blog on Culture, Gender, Raleigh Nightlife, and more
show_downloads: true
google_analytics:
#theme: jekyll-theme-minimal
remote_theme: BDHU/minimalist
color-scheme: dark
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: Home
    icon: <i class="fa-solid fa-house"></i>
    link: https://trigger-sister.github.io
  - name: About
    icon: <i class="fas fa-user-circle"></i>
    link: % post_url 2025-10-31-MANIFESTO %
  - name: Blog
    icon: <i class="fas fa-blog"></i>
    link: https://trigger-sister.github.io/WIP.html
  - name: Art
    icon: <i class="fas fa-palette"></i>
    link: https://trigger-sister.github.io/WIP.html
  - name: Contact
    icon: <i class="fas fa-pen"></i>
    link: https://trigger-sister.github.io/contact.html
