title: Not Like Other Girls
logo: /assets/img/logo.png
description: A blog on Culture, Gender, Raleigh Nightlife, and more
show_downloads: true
google_analytics:
# theme: jekyll-theme-minimal
remote_theme: BDHU/minimalist
color-scheme: dark
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: About
    icon: <i class="fa-far fa-user-circle"></i>
    link: https://trigger-sister.github.io/another-page.html
  - name: Blog
    icon: <i class="fa-brands fa-blog"></i>
    link: https://trigger-sister.github.io/another-page.html
  - name: Art
    icon: <i class="fa-fas fa-palette"></i>
    link: https://trigger-sister.github.io/another-page.html
  - name: Contact
    icon: <i class="fa-brands fa-pen"></i>
    link: https://trigger-sister.github.io/another-page.html
